version: '3.8'

services:
  # TurKey Auth API (Development)
  turkey-auth-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://turkey:turkey_password@postgres:5432/turkey_auth
      - JWT_ISSUER=http://localhost:3000
      - JWT_AUDIENCE=turkey-dev
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=turkey_auth
      - POSTGRES_USER=turkey
      - POSTGRES_PASSWORD=turkey_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turkey -d turkey_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (optional - for rate limiting and caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  default:
    name: turkey-auth-dev-network